---------------------------------------
Begin Slurm Prolog: Apr-25-2025 14:17:24
Job ID:    2533513
User ID:   dnguyen448
Account:   coc
Job name:  evaluateGene
Partition: ice-gpu
QOS:       coe-ice
---------------------------------------
Launching Python Evaluation
atl1-1-01-002-6-0.pace.gatech.edu

CondaError: Run 'conda init' before 'conda deactivate'

PARAMETER ...
Namespace(use_cpu=False, gpu='0', batch_size=216, model='pointnet2_cls_ssg_xXxHDZzzdwaIt9lBW5DFY2LqM3r', num_category=40, epoch=2, learning_rate=0.001, num_point=1024, optimizer='Adam', log_dir=None, decay_rate=0.0001, use_normals=False, process_data=False, use_uniform_sample=False, data='/storage/ice-shared/vip-vvk/data/llm_ge_data/modelnet40_normal_resampled', end_lr=0.001, seed=21, val_r=0.2, amp=True)
Load dataset ...
The size of train data is 9843
The size of test data is 2468
Traceback (most recent call last):
  File "/storage/ice1/3/9/dnguyen448/LLM-Guided-Evolution-Generic/./sota/Pointnet_Pointnet2_pytorch/train_classification.py", line 283, in <module>
    main(args)
  File "/storage/ice1/3/9/dnguyen448/LLM-Guided-Evolution-Generic/./sota/Pointnet_Pointnet2_pytorch/train_classification.py", line 168, in main
    criterion = model.get_loss()
AttributeError: module 'pointnet2_cls_ssg_xXxHDZzzdwaIt9lBW5DFY2LqM3r' has no attribute 'get_loss'
---------------------------------------
Begin Slurm Epilog: Apr-25-2025 14:17:35
Job ID:        2533513
User ID:       dnguyen448
Account:       coc
Job name:      evaluateGene
Resources:     cpu=12,gres/gpu:v100=1,mem=16G,node=1
Rsrc Used:     cput=00:03:00,vmem=0,walltime=00:00:15,mem=241348K,energy_used=0
Partition:     ice-gpu
QOS:           coe-ice
Nodes:         atl1-1-01-002-6-0
---------------------------------------
